# Jekyll Configuration
markdown: 'kramdown'
highlighter: 'rouge'
words_per_minute: 200

# Site Settings
baseurl: '/'
url: 'https://misaal-web.netlify.app'
favicon: 'assets/uploads/favicon.png'

# Site Configuration
navigation: true
subscribers: true
google_analytics: # Google Analytics ID
disqus: false # Enable Disqus
disqus_shortname: # Disqus Username

# Front Matter Defaults
defaults:
  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: 'post'
      current: 'post'
      class: 'post-template'
      subclass: 'post'
      navigation: true
      author: default
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
      current: 'page'
      class: 'page-template'
      subclass: 'page'
      navigation: true

# Jekyll Plugins
plugins_dir: ['_plugins']
plugins:
  - jekyll-paginate-v2
  - jekyll-datapage-generator

# Permalinks
permalink: '/:title'

# jekyll-paginate-v2 Configuration
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title | Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# jekyll-paginate-v2 Autopages Configuration
autopages:
  enabled: true
  tags:
    layouts:
      - 'tag.html'
    title: 'Stories tagged with :tag'
    permalink: '/tag/:tag'
  categories:
    enabled: false
  collections:
    enabled: false

# jekyll-datapage-generator Configuration
page_gen-dirs: true
page_gen:
  - data: 'authors.authors'
    template: 'author'
    name: 'username'
    dir: 'author'
