backend:
  name: github
  repo: sahlamba/misaal-web
  branch: release

publish_mode: editorial_workflow

media_folder: 'assets/uploads'

# Branding
site_url: https://misaal.co.in
display_url: https://misaal.co.in
logo_url: https://misaal.co.in/assets/images/logo_horizontal.png

collections:
  - name: 'wesbite'
    label: 'Website'
    files:
      - name: 'settings'
        label: 'Settings'
        file: '_data/settings.yml'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'string'
            required: false
          - name: 'logo'
            label: 'Logo'
            widget: 'image'
            required: false
          - name: 'logo_dark'
            label: 'Logo (Dark)'
            widget: 'image'
            required: false
          - name: 'cover'
            label: 'Cover'
            widget: 'image'
            required: false
          - name: 'contact'
            label: 'Contact & Social Media'
            widget: 'object'
            fields:
              - name: 'email'
                label: 'Email'
                widget: 'string'
                required: false
                hint: 'Example: contact@example.com'
              - name: 'twitter'
                label: 'Twitter'
                widget: 'string'
                required: false
                hint: 'Twitter username, example: @mywebsite'
              - name: 'facebook'
                label: 'Facebook Page'
                widget: 'string'
                required: false
                hint: 'Only enter FB page name, example: MyWebsite'
              - name: 'instagram'
                label: 'Instagram'
                widget: 'string'
                required: false
                hint: 'Instagram username, example: mywebsite'
              - name: 'youtube_channel'
                label: 'YouTube Channel Name'
                widget: 'string'
                required: false
                hint: 'Only enter YouTube channel name, example: MyWebsite'
      - name: 'authors'
        label: 'Authors'
        file: '_data/authors.yml'
        fields:
          - name: 'authors'
            label: 'Authors'
            widget: 'list'
            fields:
              - name: 'username'
                label: 'Username'
                widget: 'string'
              - name: 'display_name'
                label: 'Display Name'
                widget: 'string'
              - name: 'email'
                label: 'Email'
                widget: 'string'
                required: false
              - name: 'bio'
                label: 'Bio'
                widget: 'string'
                required: false
              - name: 'avatar'
                label: 'Avatar'
                widget: 'image'
                required: false
              - name: 'cover'
                label: 'Cover'
                widget: 'image'
                required: false
              - name: 'location'
                label: 'Location'
                widget: 'string'
                required: false
              - name: 'social_media'
                label: 'Social Media'
                widget: 'object'
                fields:
                  - name: 'website'
                    label: 'Website'
                    widget: 'string'
                    required: false
                  - name: 'twitter'
                    label: 'Twitter Username'
                    widget: 'string'
                    required: false
                  - name: 'facebook'
                    label: 'Facebook Username'
                    widget: 'string'
                    required: false
                  - name: 'instagram'
                    label: 'Instagram Username'
                    widget: 'string'
                    required: false
                  - name: 'linkedin'
                    label: 'LinkedIn Username'
                    widget: 'string'
                    required: false
      - name: 'tags'
        label: 'Tags'
        file: '_data/tags.yml'
        fields:
          - name: 'tags'
            label: 'Tags'
            widget: 'list'
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'string'
                required: false
              - name: 'cover'
                label: 'Cover'
                widget: 'image'
                required: false
      - name: 'team'
        label: 'Team'
        file: '_data/team.yml'
        fields:
          - name: 'members'
            label: 'Members'
            widget: 'list'
            fields:
              - name: 'display_name'
                label: 'Display Name (Full)'
                widget: 'string'
                hint: 'Example: Justin Case'
              - name: 'gender'
                label: 'Gender'
                widget: 'select'
                options: ['male', 'female']
              - name: 'bio'
                label: 'Bio'
                widget: 'string'
                pattern:
                  ['^.{1,120}$', 'Maximum allowed length is 120 characters']
              - name: 'photo'
                label: 'Photo'
                widget: 'image'
                required: false
                hint: 'Use a square photo with equal width/height for optimal design'
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'about/index.md'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'cover'
            label: 'Cover'
            widget: 'image'
            required: false
          - name: 'body'
            label: 'Body'
            widget: 'markdown'
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
        pattern: ['^.{1,90}$', 'Maximum allowed length is 90 characters']
      - name: 'description'
        label: 'Description'
        widget: 'string'
        required: false
        pattern: ['^.{0,120}$', 'Maximum allowed length is 120 characters']
        hint: 'One line description of the story, good for SEO'
      - name: 'date'
        label: 'Date'
        widget: 'datetime'
      - name: 'tags'
        label: 'Tags'
        widget: 'list'
        required: false
        minimize_collapsed: true
        # "field" is used to show tags as a list, by default it is CSV text input
        summary: '{{fields.name}}'
        field:
          name: 'name'
          label: 'Name'
          widget: 'string'
      - name: 'cover'
        label: 'Cover Photo'
        widget: 'image'
        required: false
      - name: 'youtube_video_id'
        label: 'YouTube Video ID'
        widget: 'string'
        required: false
        hint: 'YouTube Video ID is the part after v= (i.e. 365wR-wilqA in https://www.youtube.com/watch?v=365wR-wilqA)'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
