backend:
  name: github
  repo: sahlamba/misaal-web
  branch: ghost-theme

media_folder: 'assets/uploads'

collections:
  - name: 'wesbite'
    label: 'Website'
    files:
      - name: 'settings'
        label: 'Settings'
        file: '_data/settings.yml'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'string'
          - name: 'contact'
            label: 'Contact & Social Media'
            widget: 'object'
            fields:
              - name: 'email'
                label: 'Email'
                widget: 'string'
              - name: 'twitter'
                label: 'Twitter Username (without @)'
                widget: 'string'
              - name: 'facebook'
                label: 'Facebook User / Page Name'
                widget: 'string'
              - name: 'instagram'
                label: 'Instagram Username'
                widget: 'string'
      - name: 'authors'
        label: 'Authors'
        file: '_data/authors.yml'
        fields:
          - name: 'authors'
            label: 'Authors'
            widget: 'list'
            fields:
              - name: 'username'
                label: 'Username'
                widget: 'string'
              - name: 'display_name'
                label: 'Display Name'
                widget: 'string'
              - name: 'email'
                label: 'Email'
                widget: 'string'
              - name: 'bio'
                label: 'Bio'
                widget: 'string'
              - name: 'avatar'
                label: 'Avatar'
                widget: 'image'
              - name: 'cover'
                label: 'Cover'
                widget: 'image'
              - name: 'location'
                label: 'Location'
                widget: 'string'
              - name: 'social_media'
                label: 'Social Media'
                widget: 'object'
                fields:
                  - name: 'website'
                    label: 'Website'
                    widget: 'string'
                  - name: 'twitter'
                    label: 'Twitter Username (without @)'
                    widget: 'string'
                  - name: 'facebook'
                    label: 'Facebook Username'
                    widget: 'string'
                  - name: 'instagram'
                    label: 'Instagram Username'
                    widget: 'string'
                  - name: 'linkedin'
                    label: 'LinkedIn Username'
                    widget: 'string'
      - name: 'tags'
        label: 'Tags'
        file: '_data/tags.yml'
        fields:
          - name: 'tags'
            label: 'Tags'
            widget: 'list'
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'string'
              - name: 'cover'
                label: 'Cover'
                widget: 'image'
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'about/index.md'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'body'
            label: 'Body'
            widget: 'markdown'
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'date'
        label: 'Date'
        widget: 'datetime'
      - name: 'tags'
        label: 'Tags'
        widget: 'list'
        # Uncomment to show tags as a list, by default it is CSV input
        # field:
        #   name: 'name'
        #   label: 'Name'
        #   widget: 'string'
      - name: 'cover'
        label: 'Cover Photo'
        widget: 'image'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
