backend:
  name: github
  repo: sahlamba/misaal-web
  branch: ghost-theme

media_folder: 'assets/uploads'

# Branding
site_url: https://misaal-web.netlify.app
display_url: https://misaal-web.netlify.app
logo_url: https://misaal-web.netlify.app/assets/uploads/ghost.png

collections:
  - name: 'wesbite'
    label: 'Website'
    files:
      - name: 'settings'
        label: 'Settings'
        file: '_data/settings.yml'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'string'
            required: false
          - name: 'logo'
            label: 'Logo'
            widget: 'image'
            required: false
          - name: 'logo_dark'
            label: 'Logo (Dark)'
            widget: 'image'
            required: false
          - name: 'cover'
            label: 'Cover'
            widget: 'image'
            required: false
          - name: 'contact'
            label: 'Contact & Social Media'
            widget: 'object'
            fields:
              - name: 'email'
                label: 'Email'
                widget: 'string'
                required: false
              - name: 'twitter'
                label: 'Twitter Username'
                widget: 'string'
                required: false
              - name: 'facebook'
                label: 'Facebook User / Page Name'
                widget: 'string'
                required: false
              - name: 'instagram'
                label: 'Instagram Username'
                widget: 'string'
                required: false
      - name: 'authors'
        label: 'Authors'
        file: '_data/authors.yml'
        fields:
          - name: 'authors'
            label: 'Authors'
            widget: 'list'
            fields:
              - name: 'username'
                label: 'Username'
                widget: 'string'
              - name: 'display_name'
                label: 'Display Name'
                widget: 'string'
              - name: 'email'
                label: 'Email'
                widget: 'string'
                required: false
              - name: 'bio'
                label: 'Bio'
                widget: 'string'
                required: false
              - name: 'avatar'
                label: 'Avatar'
                widget: 'image'
                required: false
              - name: 'cover'
                label: 'Cover'
                widget: 'image'
                required: false
              - name: 'location'
                label: 'Location'
                widget: 'string'
                required: false
              - name: 'social_media'
                label: 'Social Media'
                widget: 'object'
                fields:
                  - name: 'website'
                    label: 'Website'
                    widget: 'string'
                    required: false
                  - name: 'twitter'
                    label: 'Twitter Username'
                    widget: 'string'
                    required: false
                    comment: Twitter account username
                  - name: 'facebook'
                    label: 'Facebook Username'
                    widget: 'string'
                    required: false
                  - name: 'instagram'
                    label: 'Instagram Username'
                    widget: 'string'
                    required: false
                  - name: 'linkedin'
                    label: 'LinkedIn Username'
                    widget: 'string'
                    required: false
      - name: 'tags'
        label: 'Tags'
        file: '_data/tags.yml'
        fields:
          - name: 'tags'
            label: 'Tags'
            widget: 'list'
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'description'
                label: 'Description'
                widget: 'string'
                required: false
              - name: 'cover'
                label: 'Cover'
                widget: 'image'
                required: false
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'about/index.md'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'cover'
            label: 'Cover'
            widget: 'image'
            required: false
          - name: 'body'
            label: 'Body'
            widget: 'markdown'
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'date'
        label: 'Date'
        widget: 'datetime'
      - name: 'tags'
        label: 'Tags'
        widget: 'list'
        required: false
        minimize_collapsed: true
        # "field" is used to show tags as a list, by default it is CSV text input
        summary: '{{fields.name}}'
        field:
          name: 'name'
          label: 'Name'
          widget: 'string'
      - name: 'cover'
        label: 'Cover Photo'
        widget: 'image'
        required: false
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
