backend:
  name: github
  repo: sahlamba/misaal-web
  branch: ghost-theme

media_folder: 'assets/uploads'

collections:
  - name: 'settings'
    label: 'Settings'
    files:
      - name: 'website'
        label: 'Website'
        file: '_data/settings.yml'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'description'
            label: 'Description'
            widget: 'string'
          - name: 'contact'
            label: 'Contact & Social Media'
            widget: 'object'
            fields:
              - name: 'email'
                label: 'Email'
                widget: 'string'
              - name: 'twitter'
                label: 'Twitter Username (without @)'
                widget: 'string'
              - name: 'facebook'
                label: 'Facebook User / Page Name'
                widget: 'string'
              - name: 'instagram'
                label: 'Instagram Username'
                widget: 'string'
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'about/index.md'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'body'
            label: 'Body'
            widget: 'markdown'
  - name: 'posts'
    label: 'Posts'
    folder: '_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'date'
        label: 'Date'
        widget: 'datetime'
      - name: 'tags'
        label: 'Tags'
        widget: 'list'
        # Uncomment to show tags as a list, by default it is CSV input
        # field:
        #   name: 'name'
        #   label: 'Name'
        #   widget: 'string'
      - name: 'cover'
        label: 'Cover Photo'
        widget: 'image'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
