title: Misaal
description: Misaal is a platform dedicated to inspire young Indian Muslims by
  sharing the stories of success from individuals of the community who have
  emerged as managers, leaders and entrepreneurs in various fields.
logo: /assets/uploads/logo_transparent.png
logo_dark: /assets/uploads/logo_transparent.png
cover: /assets/uploads/background-4.png
contact:
  email: editor@misaal.co.in
  twitter: MisaalIndia
  facebook: MisaalIndia
  instagram: misaal.co.in
  youtube_channel: UCliGDQZ3n0jGmu2N6hZUsVg
